"""
Name: Hunny Biguvu
Date: March 13, 2026
Assignment: Word Sense Disambiguation Scorer

Problem Description:
This program evaluates the accuracy of predictions produced by the
word sense disambiguation system. It compares the predicted senses
generated by the model with the correct answers provided in the key file.

Program Input:
The program takes two command line arguments:
1. The file containing the predicted answers (my-line-answers.txt)
2. The file containing the correct answers (line-key.txt)

Example usage:
python3 scorer.py my-line-answers.txt line-key.txt

Example output:
Overall Score: 92.25%

Algorithm Description:
1. Read the predicted answers file and the answer key file.
2. Store the predicted senses in a dictionary using instance IDs.
3. Extract the correct senses from the key file using regular expressions.
4. Store the correct answers in another dictionary.
5. Compare predicted senses with correct senses.
6. Count how many predictions are correct.
7. Compute the accuracy percentage.
8. Print the final score.
"""

# Import libraries for command line arguments, text processing, and math
from sys import argv
import re
import math

# Get the predicted answers file and the answer key file from command line
myAns_txtfile = argv[1]
ansKey_txtfile = argv[2]

# Variables to store file contents and dictionaries for answers
myAns_txt =""
ansKey_txt = ""
 
myAns_dir = {}       # stores my predicted answers
key_dir = {}         # stores correct answers

# Read the predicted answers file
with open(myAns_txtfile,"r", encoding="utf-16") as f:
    myAns_txt += f.read().lower()

# Read the answer key file
with open(ansKey_txtfile,"r", encoding="utf-8") as f:
    ansKey_txt += f.read().lower()

# Split files into lines for processing
myAns_txt = myAns_txt.split("\n")
ansKey_txt = ansKey_txt.split("\n")


# This function creates a dictionary of predicted answers.
# The instance ID is used as the key and the predicted sense as the value.
def creat_answer_dir():
    for line in myAns_txt:
        if not line.split():
            continue

        if len(line.split())> 2:
            parts = line.split()
            id = "".join(parts[0]+" "+parts[1]+" "+parts[2])
            sense =parts[3]
            
        else:
            id, sense = line.split()

        myAns_dir[id] = sense
       
   
# This function extracts the correct answers from the key file.
# It uses regular expressions to find the instance ID and correct sense.
def create_key_dir():
    
    for line in ansKey_txt:
        
        id_match = re.search(r'instance="(.*?)"', line)
        sense_match = re.search(r'senseid="(.*?)"', line)

        if not id_match or not sense_match:
            continue
        id = id_match.group(1)
        sense = sense_match.group(1)

        key_dir[id] = sense

# This function compares predicted senses with the correct senses.
# It counts how many predictions are correct and calculates the accuracy.
def compute_score():
    total = len(key_dir.keys())
    correct_Count = 0

    for id, sense in key_dir.items():
        if id in myAns_dir.keys():
            if sense == myAns_dir[id]:
                correct_Count += 1
            
    
    score = (correct_Count / total) * 100

    print(f"Overall Score: {score:.2f}%")

    



# Run the functions to build dictionaries and compute the final score
creat_answer_dir()
create_key_dir()
compute_score()

